apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso-frontend
  template:
    metadata:
      labels:
        app: rso-frontend
    spec:
      containers:
        - image: mista123/frontend-rso:latest
          name: frontend
          env:
            - name: db_user
              value: postgres
            - name: db_pw
              value: postgres
          ports:
            - containerPort: 8090
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: rso-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      protocol: TCP
      targetPort: server
  selector:
    app: rso-frontend