version: '2'
services:

  frontEnd:
      container_name: frontEndRSO
      image: mista123/frontend-rso:latest
      networks:
        - net
      ports:
        - 8090:8090
      environment:
        - db_user=postgres
        - db_pw=postgres

volumes:
  image-db:
    driver: local

networks:
  net:
    driver: bridge